version: "3"

services:
  #PostgreSql
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    build:
      context: ./
      dockerfile: docker/db.Dockerfile
    ports:
      - 3306
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - local-network
  #Elasticsearch
  es:
    container_name: ${COMPOSE_PROJECT_NAME}_es
    build:
      context: ./
      dockerfile: docker/es.Dockerfile
    ports:
      - "${ES_PORT}:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    networks:
      - local-network
  #PHP-FPM
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: ./
      dockerfile: docker/php.Dockerfile
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/app
      - ./docker/config/php.ini:/usr/local/etc/php/php.ini
      - ~/.bash_history:/home/docker-user/.bash_history
      - ${SATIS_SOURCE:-/dev/null}:/satis
    depends_on:
      - db
    networks:
      - local-network
  #NginX
  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    build:
      context: ./
      dockerfile: docker/web.Dockerfile
    ports:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.entrypoints=http
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.rule=HostRegexp(`laravel.test`)
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-web-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.middlewares=${COMPOSE_PROJECT_NAME}-web-https-redirect
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-web-secure.entrypoints=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-web-secure.rule=HostRegexp(`laravel.test`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-web-secure.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-web-secure.service=${COMPOSE_PROJECT_NAME}-web-https
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-web-https.loadbalancer.server.port=443
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-web-https.loadbalancer.server.scheme=https
      - traefik.docker.network=traefik
    volumes:
      - ./public:/app
      - ./docker/config/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./docker/crt:/etc/ssl
    depends_on:
      - php
    networks:
      - traefik
      - local-network

#Docker Networks
networks:
  local-network:
    driver: bridge
  traefik:
    external: true
